alter table public.device_history add column if not exists related_user_id uuid references public.users(id) on delete set null;
alter table public.device_history add column if not exists related_team_id uuid references public.teams(id) on delete set null;
alter table public.device_history add column if not exists related_establishment_id uuid references public.establishments(id) on delete set null;

create table if not exists public.device_assignment_periods (
  id uuid primary key default gen_random_uuid(),
  device_id uuid not null references public.devices(id) on delete cascade,
  user_id uuid references public.users(id) on delete set null,
  user_name text,
  user_email text,
  team_id uuid references public.teams(id) on delete set null,
  team_name text,
  establishment_id uuid references public.establishments(id) on delete set null,
  establishment_name text,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  assigned_by text not null default 'system',
  unassigned_by text,
  source text not null default 'SYSTEM',
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists idx_device_assignment_periods_device
  on public.device_assignment_periods(device_id, started_at desc);

create index if not exists idx_device_assignment_periods_open
  on public.device_assignment_periods(device_id)
  where ended_at is null;

alter table public.device_assignment_periods enable row level security;

insert into public.device_assignment_periods (
  device_id,
  user_id,
  user_name,
  user_email,
  team_id,
  team_name,
  establishment_id,
  establishment_name,
  started_at,
  assigned_by,
  source,
  reason
)
select
  d.id,
  u.id,
  nullif(trim(coalesce(u.first_name, '') || ' ' || coalesce(u.last_name, '')), ''),
  u.email,
  t.id,
  t.name,
  e.id,
  e.name,
  coalesce(d.created_at, now()),
  'system',
  'SYSTEM',
  'Initial assignment period generated by migration.'
from public.devices d
left join public.users u on u.id = d.assigned_user_id
left join public.teams t on t.id = d.team_id
left join public.establishments e on e.id = d.establishment_id
where d.assigned_user_id is not null
  and not exists (
    select 1
    from public.device_assignment_periods p
    where p.device_id = d.id
  );
